using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ink_Canvas
{
    public static class ChickenSoup {
        public static string[] OSUPlayerYuLu = new string[] {
            "Australian Genshin Impact, launch!",
            "One glance at Ding Zhen, identified as an osu! player",
            "Call MimosaM to cook two dishes for me",
            "Don't... don't delete the background image!",
            "6 seconds 800PP, I Can!",
            "osu! launch!",
            "You're right, but osu!, forgot the front, forgot the back",
            "Switching computers turned me into a disabled person",
            "Hard to maintain acc",
            "Lao Da: This is a series of pp images",
            "Look at others, persistently not farming PP, already buying houses in the newbie group",
            "Don't work so hard on osu!",
            "Can't curve a bit",
            "Experts progress so fast",
            "The gap between pass and fc is a chasm",
            "4 stars is a huge open world of sudden death (",
            "I am going to become an OWC player!",
            "Tap and jump",
            "I seem to be a bit rare",
            "Drank this as a child and learned strong doubles with my fingers",
            "90bpm grinding old man",
            "Damn, realized I've never fc'd a series of images",
            "oshit!",
            "hso!",
            "Not fun!",
            "Obtuse angle jumps are really disgusting",
            "Oh my god, O!",
            "Someone hit 2000 again"
        };

        public static string[] MingYanJingJu = new string[] {
            "老骥伏枥，志在千里；烈士暮年，壮心不已",
            "有志者，事竟成",
            "有志者自有千方百计，无志者只感千难万难",
            "有志的人战天斗地，无志的人怨天恨地",
            "有伟大志向的人，都可以成为圣人。",
            "人的志向，应在千里之外。",
            "人不在于地位的高低，而在于志向的远大。",
            "人的志向，应崇高而远大。",
            "立志没有所谓过迟",
            "鸟不展翅膀难高飞",
            "不怕路远，就怕志短",
            "当今之世，舍我其谁",
            "立志不坚，终不济事",
            "鸟贵有翼，人贵有志",
            "少年立志要远大，持身要紧严立志不高，则溺于流俗；",
            "持身不严，则入于匪辞",
            "人若有志，万事可为",
            "心志要坚，意趣要乐",
            "胸无大志，枉活一世",
            "燕雀安知鸿鹄之志哉",
            "一人立志，万夫莫敌",
            "鹰爱高飞，鸦栖一枝",
            "治天下者必先立其志",
            "强行者有志",
            "志当存高远",
            "百学须先立志",
            "以天下为己任",
            "志，气之帅也",
            "才自清明志自高",
            "褴褛衣内可藏志",
            "无所求则无所获",
            "慷慨丈夫志，可以耀锋芒",
            "母鸡的理想不过是一把糠",
            "男儿千年志，吾生未有涯",
            "男儿四方志，岂久困泥沙",
            "男子千年志，吾生未有涯",
            "穷且益坚，不坠青云之志",
            "人生志气立，所贵功业昌",
            "生无一锥土，常有四海心",
            "无志愁压头，有志能搬山",
            "心随朗月高，志与秋霜洁",
            "胸有凌云志，无高不可攀",
            "雄心志四海，万里望风尘",
            "一分事业心能抵十分特权",
            "有志登山顶，无志站山脚",
            "丈夫清万里，谁能扫一室",
            "丈夫四海志，万里犹比邻",
            "丈夫志不大，何以佐乾坤",
            "丈夫志气薄，儿女安得知",
            "志不立，天下无可成之事",
            "志高山峰矮，路从脚下伸",
            "壮志与毅力是事业的双翼",
            "成功是别人失败时还在坚持",
            "贫不足羞，可羞是贫而无志",
            "虽长不满七尺，而心雄万丈",
            "有志者能使石头长出青草来",
            "志之难也，不在胜人，在自胜",
            "有志始知蓬莱近，无为总觉咫尺远",
            "不要在夕阳西下时幻想，要在旭日东升时努力",
            "立志是事业的大门，工作是登门入室的的旅途",
            "一个人如果胸无大志，既使再有壮丽的举动也称不上是伟人",
            "志不立，如无舵这舟，无衔之马，漂荡奔逸，终亦何所底乎",
            "有志不在年高，无志空活百岁",
        };

        public static string[] GaoKaoPhrases = new string[] {
            "以梦为马，不负韶华。祝你高考顺利，未来可期！",
            "高考顺利，愿你乘风破浪，前程似锦！",
            "愿你高考顺利，不负韶华，梦想成真！",
            "高考必胜，愿你展翅高飞，未来可期！",
            "愿你不畏困难，勇往直前，高考成绩如你所愿，未来更加光明。",
            "高考将至，愿你所学皆精，所考皆通，一鸣惊人，一举夺魁！",
            "十年磨一剑，今朝试锋芒。高考顺利，未来可期！",
            "恭祝，恭祝，此战青云平步。祝高考金榜题名。",
        };
    }
}
